/**
 * @fileoverview gRPC-Web generated client stub for predictor
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: predictor.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.predictor = require('./predictor_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.predictor.PredictClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.predictor.PredictPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.predictor.ImageRequest,
 *   !proto.predictor.PredictionReply>}
 */
const methodDescriptor_Predict_PredictRoPaSc = new grpc.web.MethodDescriptor(
  '/predictor.Predict/PredictRoPaSc',
  grpc.web.MethodType.UNARY,
  proto.predictor.ImageRequest,
  proto.predictor.PredictionReply,
  /**
   * @param {!proto.predictor.ImageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.predictor.PredictionReply.deserializeBinary
);


/**
 * @param {!proto.predictor.ImageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.predictor.PredictionReply)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.predictor.PredictionReply>|undefined}
 *     The XHR Node Readable Stream
 */
proto.predictor.PredictClient.prototype.predictRoPaSc =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/predictor.Predict/PredictRoPaSc',
      request,
      metadata || {},
      methodDescriptor_Predict_PredictRoPaSc,
      callback);
};


/**
 * @param {!proto.predictor.ImageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.predictor.PredictionReply>}
 *     Promise that resolves to the response
 */
proto.predictor.PredictPromiseClient.prototype.predictRoPaSc =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/predictor.Predict/PredictRoPaSc',
      request,
      metadata || {},
      methodDescriptor_Predict_PredictRoPaSc);
};


module.exports = proto.predictor;

