"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ImageRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BASE64IMAGE_FIELD_NUMBER: builtins.int
    base64image: builtins.str
    def __init__(
        self,
        *,
        base64image: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["base64image", b"base64image"]) -> None: ...

global___ImageRequest = ImageRequest

@typing_extensions.final
class PredictionReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PREDICTEDCLASS_FIELD_NUMBER: builtins.int
    CONFIDENCE_FIELD_NUMBER: builtins.int
    predictedClass: builtins.int
    confidence: builtins.float
    def __init__(
        self,
        *,
        predictedClass: builtins.int = ...,
        confidence: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["confidence", b"confidence", "predictedClass", b"predictedClass"]) -> None: ...

global___PredictionReply = PredictionReply
